doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AccountManagerAccount:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/AccountManager/Account/Provider/Entity'
              prefix: 'App\AccountManager\Account\Provider\Entity'
              alias: App
            AccountManagerBudget:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/AccountManager/Budget/Infrastructure/Entity'
              prefix: 'App\AccountManager\Budget\Infrastructure\Entity'
              alias: App
            AccountManagerTransaction:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/AccountManager/Transaction/Provider/Entity'
              prefix: 'App\AccountManager\Transaction\Provider\Entity'
              alias: App
            CoreSecurity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Security/Infrastructure/Entity'
                prefix: 'App\Core\Security\Infrastructure\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: ''
            use_savepoints: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
