core_home:
    resource:
        path: ../src/Core/Home/Application/Controller/
        namespace: App\Core\Home\Application\Controller
    type: attribute

core_security:
    resource:
        path: ../src/Core/Security/Application/Controller/
        namespace: App\Core\Security\Application\Controller
    type: attribute

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
