core_home:
    resource:
        path: ../src/Core/Home/Infrastructure/Controller/
        namespace: App\Core\Home\Infrastructure\Controller
    type: attribute

core_security:
    resource:
        path: ../src/Core/Security/Infrastructure/Controller/
        namespace: App\Core\Security\Infrastructure\Controller
    type: attribute

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
