account_manager_budget:
  resource:
    path: ../src/AccountManager/Budget/Application/Controller/
    namespace: App\AccountManager\Budget\Application\Controller
  type: attribute
  prefix: '/gestion-de-compte/budget'
  name_prefix: 'app_account_manager_budget_'

account_manager_account:
  resource:
    path: ../src/AccountManager/Account/Application/Controller/
    namespace: App\AccountManager\Account\Application\Controller
  type: attribute
  prefix: '/gestion-de-compte/compte'
  name_prefix: 'app_account_manager_account_'

core_home:
  resource:
    path: ../src/Core/Home/Application/Controller/
    namespace: App\Core\Home\Application\Controller
  type: attribute

core_security:
  resource:
    path: ../src/Core/Security/Application/Controller/
    namespace: App\Core\Security\Application\Controller
  type: attribute
